apiVersion: apps/v1
kind: Deployment
metadata:
  name: stormshare-prod-deployment
  namespace: biocomplexity
  labels:
    app: stormshare-prod
spec:
#  replicas: 1
  selector:
    matchLabels:
      app: stormshare-prod
  template:
    metadata:
      labels:
        app: stormshare-prod
    spec:
      containers:
      - name: stormshare-prod-container
        image: ghcr.io/nssac/nsf_crisp_2019_stormshare_backend:{{ .Values.version.nsf_crisp_2019_stormshare_backend }}
        ports:
        - containerPort: 80
        env:
#        - name:
#          value: ""
        - name: "root_path"
          valueFrom:
            secretKeyRef:
              name: stormshare-prod-secrets
              key: root_path
        - name: "db_schema"
          valueFrom:
            secretKeyRef:
              name: stormshare-prod-secrets
              key: db_schema
        - name: "db_connection"
          valueFrom:
            secretKeyRef:
              name: stormshare-prod-secrets
              key: db_connection
        - name: "email_config"
          valueFrom:
            secretKeyRef:
              name: stormshare-prod-secrets
              key: email_config                 
        resources:
          requests:
            memory: "2024Mi"
            cpu: "50m"
          limits:
            memory: "3024Mi"
            cpu: "100m"
            

