apiVersion: v1
kind: Service
metadata:
  name: stormshare-prod-service
  namespace: biocomplexity
spec:
  selector:
    app: stormshare-prod
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
