apiVersion: apps/v1
kind: Deployment
metadata:
  name: stormshare-dev-deployment
  namespace: biocomplexity
  labels:
    app: stormshare-dev
spec:
  #replicas: 2
  selector:
    matchLabels:
      app: stormshare-dev
  template:
    metadata:
      labels:
        app: stormshare-dev
    spec:
      containers:
      - name: stormshare-dev-container
        image: ghcr.io/nssac/nsf_crisp_2019_stormshare_backend:{{ .Values.version.nsf_crisp_2019_stormshare_backend }}
        ports:
        - containerPort: 80
        env:
#        - name:
#          value: ""
        - name: "root_path"
          valueFrom:
            secretKeyRef:
              name: stormshare-dev-secrets
              key: root_path
        - name: "db_schema"
          valueFrom:
            secretKeyRef:
              name: stormshare-dev-secrets
              key: db_schema
        - name: "db_connection"
          valueFrom:
            secretKeyRef:
              name: stormshare-dev-secrets
              key: db_connection
        - name: "email_config"
          valueFrom:
            secretKeyRef:
              name: stormshare-dev-secrets
              key: email_config          
        resources:
          requests:
            memory: "2024Mi"
            cpu: "4"
          limits:
            memory: "8096Mi"
            cpu: "8"
            

