# websearch/base/crawler-deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawler
spec:
  replicas: 1
  selector:
    matchLabels: {app: crawler}
  template:
    metadata:
      labels: {app: crawler}
    spec:
      containers:
        - name: crawler
          image: laituanmanh/websearch-crawler:latest
          ports:
            - containerPort: 3001
          env:
            - {name: NODE_ENV,        value: "production"}
            - {name: PORT,            value: "3001"}
            - {name: LOG_LEVEL,       value: "info"}
            - {name: FLARESOLVERR_URL,value: "http://flaresolverr:8191/v1"}
          volumeMounts:
            - {name: crawler-storage, mountPath: /app/storage}
      volumes:
        - name: crawler-storage
          persistentVolumeClaim: {claimName: crawler-storage}

