# websearch/base/flaresolverr-deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaresolverr
spec:
  replicas: 1
  selector:
    matchLabels: {app: flaresolverr}
  template:
    metadata:
      labels: {app: flaresolverr}
    spec:
      containers:
        - name: flaresolverr
          image: 21hsmw/flaresolverr:nodriver
          ports:
            - containerPort: 8191
          env:
            - {name: LOG_LEVEL, value: "info"}
            - {name: TZ,        value: "UTC"}

