apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bii-pgadmin-pvc-2
  namespace: biocomplexity
spec:
  storageClassName: csi-rbd-sc
  accessModes:
    - ReadOnlyMany  #must be the same as PersistentVolume
  resources:
    requests:
      storage: 10Gi
